In [51]:
import numpy as np

In [52]:
fint = open("Intervalli confidenza.txt", "r")
fout = open("output.txt", "r")

for line in fint.readlines():
    print(line)

546.48	563.90	531.86	555.30	584.26	644.46	439.54	484.84	487.51	507.01

49.13	50.69	52.34	54.64	53.05	58.51	38.81	42.81	37.14	38.62

154.64	159.56	97.19	101.47	182.15	200.91	69.06	76.18	64.34	66.92

1060.11	1093.89	788.34	823.08	1309.64	1444.60	691.94	763.24	1006.56	1046.80

125.53	129.53	87.19	91.03	129.90	143.28	66.23	73.05	137.70	143.20

405.31	418.23	320.01	334.11	445.59	491.51	166.31	183.45	207.95	216.27

91.03	93.93	73.36	76.60	99.71	109.99	50.17	55.33	61.92	64.40

163.55	168.77	88.21	92.09	189.78	209.34	54.74	60.38	70.33	73.15

32.40	33.44	12.58	13.14	50.71	55.93	6.81	7.51	3.89	4.05

91.71	94.63	65.01	67.87	181.31	199.99	39.22	43.26	63.38	65.92



In [ ]:
dati = np.zeros((10, 5, 27))

i=0
j=0
k=0
for line in fout.readlines():
    if "Impiegato" not in line and line != "\n":
        if i>= 10:
            i=0
            k+=1
        j=0
        res = [x.strip() for x in line.split()]
        for el in res[1:]:
            print(dati)
            dati[i][j][k] = el
            j+=1
        i+=1
        
print(dati)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
[[[397.063782   0.         0.       ...   0.         0.         0.      ]
  [  0.         0.         0.       ...   0.         0.         0.      ]
  [  0.         0.         0.       ...   0.         0

IndexError: index 27 is out of bounds for axis 0 with size 27